### ISSUE TITLE
Incompatible with the latest DT builds

### ISSUE THREAD

**Issue by Sunconure11** [odorousrex/DynamicTreesTraverse#5]
With the new additions to DT, this mod is now incompatible with newer builds of Dynamic Trees.

**Comment by corgiblu** [comment]
https://paste.ee/p/AWNeb crash log, seems to be my issue too.

**Comment by ScienceDrummer** [comment]
Seems to be my issue as well. With Dynamic Surroundings added to the mix, I get this crash report with it.

Regular Crash Log: https://paste.dimdev.org/eqosirital.md
Dynamic Surroundings Crash Report: https://paste.dimdev.org/soxedakije.rb

**Comment by Serifina** [comment]
I've also had a problem with it throwing compatability errors. Full log file attached. The relevant portion of the log:

> [14:45:49] [main/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod dynamictrees (Dynamic Trees) requires [dttraverse@(1.2,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3930) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

[DTLog.txt](https://github.com/odorousrex/DynamicTreesTraverse/files/2621627/DTLog.txt)

**Comment by Sunconure11** [comment]
Still crashes.

[latest.log](https://github.com/odorousrex/DynamicTreesTraverse/files/2626037/latest.log)

**Comment by metalyc** [comment]
I have no crashes by using the Beta dttraverse-1.5.jar

**Comment by Sunconure11** [comment]
I think this issue applies again. @odorousrex 

https://pastebin.com/DE8YSkG2
